# Generated by Django 3.2.5 on 2022-05-29 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Only alphanumeric characters are allowed', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]*$', 'Only alphanumeric characters are allowed')], verbose_name='username'),
        ),
    ]
